<section>
    <h3><i class="fa fa-comment"></i> Użytkownik napisał:
        <small> 2016-06-19 11:27:04</small>
    </h3>
    <p> Świetny post! Dziękuję za wyśmienity artykuł, był bardzo przydatny! </p>

    <h3><i class="fa fa-comment"></i> Użytkownik napisał:
        <small> 2016-06-19 18:27:04</small>
    </h3>
    <p> Świetny post! Dziękuję za wyśmienity artykuł, był bardzo przydatny! </p>
</section>