<section name="leave_comment_section">
    <div class="well">
        <h4><i class="fa fa-paper-plane-o"></i> Zostaw komentarz</h4>
        <form role="form">
            <div class="form-group">
                <label for="comment">Treść komentarza:</label>
                <textarea required class="form-control" rows="3" placeholder="Wpisz tekst" id="comment"></textarea>
                <label for="signature">Twoja nazwa:</label>
                <input required type="text" class="form-control" placeholder="Wpisz swoją nazwę" id="signature"></input>
                <label for="email">Twój adres email</label>
                <input type="email" class="form-control" placeholder="Wpisz adres e-mail" id="email"></input>
            </div>
            <button type="submit" class="btn btn-primary"><i class="fa fa-reply"></i> Submit</button>
        </form>
    </div>
</section>