<form id="categories_table">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr class="table-row">
                    <th></th>
                    <th>Nazwa</th>
                    <th>Opis</th>
                    <th>Liczba</th>
                </tr>
            </thead>
            <tbody>
                <?php echo $categoriesTable; ?>
            </tbody>
        </table>
    </div>
    <button type="submit"></button>
</form>