-- MySQL Script generated by MySQL Workbench
-- 06/19/16 11:57:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema theblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema theblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `theblog` DEFAULT CHARACTER SET utf8 ;
USE `theblog` ;

-- -----------------------------------------------------
-- Table `theblog`.`blog_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theblog`.`blog_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_nickname` VARCHAR(45) NOT NULL,
  `user_first_name` VARCHAR(45) NULL,
  `user_last_name` VARCHAR(45) NULL,
  `user_email` VARCHAR(45) NULL,
  `user_is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_nickname_UNIQUE` (`user_nickname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theblog`.`blog_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theblog`.`blog_tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NOT NULL,
  `tag_clean_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_name_UNIQUE` (`tag_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theblog`.`blog_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theblog`.`blog_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `category_clean_name` VARCHAR(45) NULL,
  `category_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `category_created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `category_created_by` INT UNSIGNED NOT NULL,
  `category_parent_id` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC),
  INDEX `category_created_by_idx` (`category_created_by` ASC),
  CONSTRAINT `category_created_by`
    FOREIGN KEY (`category_created_by`)
    REFERENCES `theblog`.`blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `theblog`.`blog_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theblog`.`blog_post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_title` VARCHAR(144) NOT NULL,
  `post_title_clean` VARCHAR(45) NULL,
  `post_content` TEXT NOT NULL,
  `post_created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `post_created_by` INT UNSIGNED NOT NULL,
  `post_edited_on` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `post_edited_by` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `post_title_UNIQUE` (`post_title` ASC),
  INDEX `post_created_by_id_idx` (`post_created_by` ASC),
  CONSTRAINT `post_created_by_id`
    FOREIGN KEY (`post_created_by`)
    REFERENCES `theblog`.`blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theblog`.`blog_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theblog`.`blog_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment_parent_post_id` INT UNSIGNED NOT NULL,
  `comment_parent_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `comment_content` TEXT NOT NULL,
  `comment_author_name` VARCHAR(45) NULL,
  `comment_author_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `comment_read` TINYINT(1) NOT NULL DEFAULT 0,
  `comment_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `comment_created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `comment_parent_post_id_idx` (`comment_parent_post_id` ASC),
  INDEX `comment_author_id_idx` (`comment_author_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `comment_parent_id_idx` (`comment_parent_id` ASC),
  CONSTRAINT `comment_parent_post_id`
    FOREIGN KEY (`comment_parent_post_id`)
    REFERENCES `theblog`.`blog_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_author_id`
    FOREIGN KEY (`comment_author_id`)
    REFERENCES `theblog`.`blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_parent_id`
    FOREIGN KEY (`comment_parent_id`)
    REFERENCES `theblog`.`blog_comment` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theblog`.`blog_posts_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theblog`.`blog_posts_categories` (
  `category_id` INT UNSIGNED NOT NULL,
  `post_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`category_id`, `post_id`),
  INDEX `post_id_idx` (`post_id` ASC),
  CONSTRAINT `posts_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `theblog`.`blog_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categorys_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `theblog`.`blog_post` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theblog`.`blog_posts_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theblog`.`blog_posts_tags` (
  `post_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_id`, `tag_id`),
  INDEX `tag_id_idx` (`tag_id` ASC),
  CONSTRAINT `tags_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `theblog`.`blog_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `posts_tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `theblog`.`blog_tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
